import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const modalSource = fs.readFileSync(new URL('../src/components/common/Modal.jsx', import.meta.url), 'utf8');
const changePasswordSource = fs.readFileSync(new URL('../src/components/common/ChangePasswordModal.jsx', import.meta.url), 'utf8');
const protectedRouteSource = fs.readFileSync(new URL('../src/components/auth/ProtectedRoute.jsx', import.meta.url), 'utf8');
const scanQrSource = fs.readFileSync(new URL('../src/pages/student/ScanQrPage.jsx', import.meta.url), 'utf8');
const facultyQrSource = fs.readFileSync(new URL('../src/pages/faculty/QrAttendancePage.jsx', import.meta.url), 'utf8');
const facultyAttendanceSource = fs.readFileSync(new URL('../src/pages/faculty/TakeAttendancePage.jsx', import.meta.url), 'utf8');
const facultyPeriodApiSource = fs.readFileSync(new URL('../src/api/academicsExtra.js', import.meta.url), 'utf8');
const singleFlightSource = fs.readFileSync(new URL('../src/utils/requestSingleFlight.js', import.meta.url), 'utf8');
const facultyPeriodScopeSource = fs.readFileSync(new URL('../src/utils/facultyPeriodScope.js', import.meta.url), 'utf8');
const studentLeaveSource = fs.readFileSync(new URL('../src/pages/student/StudentLeaveRequestsPage.jsx', import.meta.url), 'utf8');
const leaveReviewSource = fs.readFileSync(new URL('../src/pages/shared/LeaveReviewPage.jsx', import.meta.url), 'utf8');
const calendarDateSource = fs.readFileSync(new URL('../src/utils/calendarDate.js', import.meta.url), 'utf8');
const indexHtmlSource = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const attendanceTrendSource = fs.readFileSync(new URL('../src/components/charts/AttendanceTrendChart.jsx', import.meta.url), 'utf8');
const errorPageSource = fs.readFileSync(new URL('../src/components/common/ErrorPage.jsx', import.meta.url), 'utf8');
const errorBoundarySource = fs.readFileSync(new URL('../src/components/common/AppErrorBoundary.jsx', import.meta.url), 'utf8');
const statusPageSource = fs.readFileSync(new URL('../src/pages/auth/CheckRequestStatusPage.jsx', import.meta.url), 'utf8');
const registrationSource = fs.readFileSync(new URL('../src/pages/auth/RequestRegistrationPage.jsx', import.meta.url), 'utf8');
const pendingRegistrationSource = fs.readFileSync(new URL('../src/pages/hod/PendingRegistrationsPage.jsx', import.meta.url), 'utf8');
const passwordFieldSource = fs.readFileSync(new URL('../src/components/common/PasswordField.jsx', import.meta.url), 'utf8');
const photoUploadSource = fs.readFileSync(new URL('../src/components/common/PhotoUpload.jsx', import.meta.url), 'utf8');
const loginSource = fs.readFileSync(new URL('../src/pages/auth/LoginPage.jsx', import.meta.url), 'utf8');
const topbarSource = fs.readFileSync(new URL('../src/components/layout/Topbar.jsx', import.meta.url), 'utf8');
const desktopNavSource = fs.readFileSync(new URL('../src/components/layout/DesktopNav.jsx', import.meta.url), 'utf8');
const sidebarProfileSource = fs.readFileSync(new URL('../src/components/layout/SidebarProfile.jsx', import.meta.url), 'utf8');
const academicManagementSource = fs.readFileSync(new URL('../src/pages/hod/AcademicManagementPage.jsx', import.meta.url), 'utf8');
const skeletonSource = fs.readFileSync(new URL('../src/components/common/Skeleton.jsx', import.meta.url), 'utf8');
const profileSource = fs.readFileSync(new URL('../src/pages/shared/ProfilePage.jsx', import.meta.url), 'utf8');
const accountManagementSource = fs.readFileSync(new URL('../src/pages/hod/AccountManagementPage.jsx', import.meta.url), 'utf8');
const hodStudentsSource = fs.readFileSync(new URL('../src/pages/hod/StudentsPage.jsx', import.meta.url), 'utf8');
const hodFacultySource = fs.readFileSync(new URL('../src/pages/hod/FacultyPage.jsx', import.meta.url), 'utf8');
const facultyStudentsSource = fs.readFileSync(new URL('../src/pages/faculty/FacultyStudentsPage.jsx', import.meta.url), 'utf8');
const appSource = fs.readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8');
const navigationSource = fs.readFileSync(new URL('../src/components/layout/navigation.js', import.meta.url), 'utf8');
const changePasswordPageSource = fs.readFileSync(new URL('../src/pages/shared/ChangePasswordPage.jsx', import.meta.url), 'utf8');
const resetPasswordSource = fs.readFileSync(new URL('../src/pages/auth/ResetPasswordPage.jsx', import.meta.url), 'utf8');
const forgotPasswordSource = fs.readFileSync(new URL('../src/pages/auth/ForgotPasswordPage.jsx', import.meta.url), 'utf8');
const clientSource = fs.readFileSync(new URL('../src/api/client.js', import.meta.url), 'utf8');
const periodControllerSource = fs.readFileSync(new URL('../../server/src/controllers/periodTemplateController.js', import.meta.url), 'utf8');
const attendanceControllerSource = fs.readFileSync(new URL('../../server/src/controllers/attendanceController.js', import.meta.url), 'utf8');
const errorMessagesSource = fs.readFileSync(new URL('../src/utils/errorMessages.js', import.meta.url), 'utf8');
const miscApiSource = fs.readFileSync(new URL('../src/api/misc.js', import.meta.url), 'utf8');
const usersApiSource = fs.readFileSync(new URL('../src/api/users.js', import.meta.url), 'utf8');
const themeSource = fs.readFileSync(new URL('../src/context/ThemeContext.jsx', import.meta.url), 'utf8');
const authLayoutSource = fs.readFileSync(new URL('../src/components/layout/AuthLayout.jsx', import.meta.url), 'utf8');
const mobileNavSource = fs.readFileSync(new URL('../src/components/layout/MobileNav.jsx', import.meta.url), 'utf8');
const dashboardLayoutSource = fs.readFileSync(new URL('../src/components/layout/DashboardLayout.jsx', import.meta.url), 'utf8');
const mainSource = fs.readFileSync(new URL('../src/main.jsx', import.meta.url), 'utf8');
const trendChartSource = fs.readFileSync(new URL('../src/components/charts/AttendanceTrendChart.jsx', import.meta.url), 'utf8');
const monthlyChartSource = fs.readFileSync(new URL('../src/components/charts/MonthlyAttendanceChart.jsx', import.meta.url), 'utf8');
const subjectChartSource = fs.readFileSync(new URL('../src/components/charts/SubjectAttendanceChart.jsx', import.meta.url), 'utf8');
const studentDashboardSource = fs.readFileSync(new URL('../src/pages/student/StudentDashboardPage.jsx', import.meta.url), 'utf8');
const hodDashboardSource = fs.readFileSync(new URL('../src/pages/hod/HodDashboardPage.jsx', import.meta.url), 'utf8');
const peopleSource = fs.readFileSync(new URL('../src/pages/hod/PeoplePage.jsx', import.meta.url), 'utf8');
const notificationsSource = fs.readFileSync(new URL('../src/pages/student/StudentNotificationsPage.jsx', import.meta.url), 'utf8');
const notificationPanelSource = fs.readFileSync(new URL('../src/components/layout/NotificationPanel.jsx', import.meta.url), 'utf8');
const indexCssSource = fs.readFileSync(new URL('../src/index.css', import.meta.url), 'utf8');


test('first-login and QR scanner contracts remain accessible and server-validated', () => {
  assert.match(protectedRouteSource, /requiresPasswordChange/);
  assert.match(protectedRouteSource, /change-password/);
  assert.match(scanQrSource, /getUserMedia/);
  assert.match(scanQrSource, /BarcodeDetector/);
  assert.match(scanQrSource, /jsQR/);
  assert.match(scanQrSource, /Camera permission is required/);
  assert.match(scanQrSource, /Enter QR link manually/);
  assert.match(scanQrSource, /qrApi\.scan/);
  assert.match(facultyQrSource, /toast\.error/);
  assert.match(facultyQrSource, /getFriendlyError/);
  assert.match(facultyQrSource, /statsError/);
  assert.match(facultyQrSource, /filterFacultyPeriods/);
  assert.match(facultyQrSource, /getByDay\(getDayName\(date\), \{ classId, subjectId \}\)/);
  assert.match(facultyQrSource, /No periods for this subject/);
  assert.match(facultyAttendanceSource, /filterFacultyPeriods/);
  assert.match(facultyAttendanceSource, /getByDay\(getDayName\(date\), \{ classId, subjectId \}\)/);
  assert.match(facultyAttendanceSource, /setRoster\(null\)/);
  assert.doesNotMatch(facultyQrSource, /alert\(/);
});

test('all error states use safe custom page contracts', () => {
  assert.match(errorPageSource, /Page not found|Something went wrong/);
  assert.match(errorPageSource, /state\.kind === 'network'/);
  assert.match(errorPageSource, /forbidden: ShieldAlert/);
  assert.match(errorBoundarySource, /<ErrorPage error=\{this\.state\.error\}/);
  assert.match(statusPageSource, /couldn't find that registration request/i);
  assert.match(statusPageSource, /visibilitychange/);
  assert.match(statusPageSource, /15000/);
  assert.match(statusPageSource, /AR-\[A-Z0-9\]\{4\}/);
  assert.match(statusPageSource, /private status link/i);
  assert.match(registrationSource, /statusCode/);
  assert.match(registrationSource, /Status reference/);
  assert.doesNotMatch(registrationSource, /PrivateDetail label="Status token"/);
});
test('registration and profile UX contracts include DOB, password checks, and secure photo upload', () => {
  assert.match(registrationSource, /dateOfBirth/);
  assert.match(registrationSource, /calculateAge/);
  assert.match(registrationSource, /PasswordField/);
  assert.match(registrationSource, /PhotoUpload/);
  assert.match(passwordFieldSource, /PASSWORD_CHECK_LABELS/);
  assert.match(passwordFieldSource, /minLength=\{12\}/);
  assert.match(passwordFieldSource, /Passwords do not match/);
  assert.match(passwordFieldSource, /aria-label/);
  assert.match(photoUploadSource, /3 MB/);
  assert.match(photoUploadSource, /Only JPG, PNG and WebP/);
});
test('role-aware registration and profile identity contracts remain visible', () => {
  assert.match(loginSource, /Request student access/);
  assert.match(loginSource, /Request faculty access/);
  assert.match(registrationSource, /requestedRole/);
  assert.match(registrationSource, /departmentApi/);
  assert.doesNotMatch(registrationSource, /employeeId|registerNumber/);
  assert.match(pendingRegistrationSource, /Assign and approve/);
  assert.match(pendingRegistrationSource, /assignedIdentifier/);
  assert.match(pendingRegistrationSource, /required/i);
  assert.match(pendingRegistrationSource, /identifierLabel/);
  assert.match(pendingRegistrationSource, /Assign and approve/);
  assert.match(pendingRegistrationSource, /required only|Required/);
  assert.match(sidebarProfileSource, /user\?\.avatarUrl/);
  assert.match(sidebarProfileSource, /Sign out/);
  assert.match(topbarSource, /Open profile menu/);
  assert.match(topbarSource, /Settings/);
  assert.match(topbarSource, /Change password/);
  assert.match(topbarSource, /user\?\.avatarUrl/);
  assert.match(topbarSource, /departmentLabel/);
  assert.match(profileSource, /import \{ useEffect, useState \} from 'react'/);
  assert.match(profileSource, /canEditPhoto/);
  assert.match(profileSource, /canEditPhoto/);
  assert.doesNotMatch(profileSource, /Student profile photos are set during registration and cannot be changed here/);
  assert.match(profileSource, /Department/);
  assert.match(profileSource, /Program/);
  assert.match(profileSource, /Semester/);
  assert.match(profileSource, /class\?\.semester\?\.label/);
  assert.match(profileSource, /Class/);
  assert.match(profileSource, /const payload = \{ email: form\.email\.trim\(\), phone: form\.phone\.trim\(\) \}/);
  assert.match(profileSource, /form\.avatarUrl !== \(user\?\.avatarUrl \|\| ''\)/);
  assert.match(hodStudentsSource, /managedRole="user"/);
  assert.match(hodFacultySource, /managedRole="admin"/);
  assert.match(accountManagementSource, /managedRole/);
  assert.match(accountManagementSource, /departmentFilter/);
  assert.match(accountManagementSource, /department: departmentFilter/);
  assert.match(accountManagementSource, /semester: managedRole === 'user'/);
  assert.match(accountManagementSource, /tutorsOnly/);
  assert.match(accountManagementSource, /sortBy/);
  assert.match(accountManagementSource, /sortOrder/);
  assert.match(accountManagementSource, /PortalPopover/);
  assert.match(accountManagementSource, /All Departments/);
  assert.match(accountManagementSource, /label="Department"/);
  assert.match(accountManagementSource, /Temporary password generated/);
  assert.match(accountManagementSource, /passwordExpiresAt/);
  assert.match(accountManagementSource, /must be changed after sign-in/);
  assert.match(accountManagementSource, /Shown once/);
  assert.match(accountManagementSource, /Reset device/);
  assert.match(appSource, /path="students" element=\{<HodStudentsPage \/>\}/);
  assert.match(appSource, /path="faculty" element=\{<HodFacultyPage \/>\}/);
  assert.match(appSource, /HodTutorsPage/);
  assert.match(appSource, /path="tutors" element=\{<HodTutorsPage \/>\}/);
  assert.match(navigationSource, /to: '\/hod\/students'/);
  assert.match(navigationSource, /to: '\/hod\/faculty'/);
  assert.match(navigationSource, /to: '\/hod\/tutors'/);
  assert.match(navigationSource, /super_admin: 'Head of Department'/);
  assert.doesNotMatch(navigationSource, /System administrator|Administrator/);
  assert.match(desktopNavSource, /attendance-register\.sidebar-collapsed/);
  assert.match(desktopNavSource, /Collapse navigation/);
  assert.match(academicManagementSource, /canManageDepartmentAcademics/);
  assert.match(academicManagementSource, /Add semester/);
  assert.match(academicManagementSource, /semesterCount/);
  assert.match(profileSource, /departmentApi\.publicOptions/);
  assert.match(profileSource, /payload\.department/);
  assert.match(skeletonSource, /SkeletonCard/);
});

test('Topbar search and notification polling are cancellable and visibility-aware', () => {
  assert.match(topbarSource, /new AbortController\(\)/);
  assert.match(topbarSource, /controller\.abort\(\)/);
  assert.match(topbarSource, /document\.visibilityState === 'hidden'/);
  assert.match(topbarSource, /visibilitychange/);
  assert.match(topbarSource, /clearInterval\(interval\)/);
  assert.match(miscApiSource, /global: \(q, config = \{\}\)/);
});

test('topbar logout and authorization feedback contracts remain safe', () => {
  assert.match(topbarSource, /const \{ user, logout \} = useAuth\(\)/);
  assert.match(topbarSource, /await logout\(\)/);
  assert.match(errorMessagesSource, /if \(status === 403\) return serverMessage/);
  assert.match(errorMessagesSource, /const isNetworkFailure/);
  assert.match(clientSource, /runSingleFlight/);
  assert.match(clientSource, /config\._retry/);
  assert.match(themeSource, /attendance-register\.theme/);
  assert.match(themeSource, /resolvedTheme/);
  assert.match(authLayoutSource, /Attendance Register/);
  assert.doesNotMatch(authLayoutSource, /\bv1[567](?:\.\d+)*\b/i);
});

test('device binding and password form contracts remain explicit', () => {
  assert.match(clientSource, /X-Device-Id/);
  assert.match(clientSource, /getDeviceId/);
  assert.match(usersApiSource, /resetDevice/);
  assert.match(usersApiSource, /config = \{\}/);
  assert.match(accountManagementSource, /AbortController/);
  assert.match(facultyStudentsSource, /AbortController/);
  assert.match(usersApiSource, /getSummary/);
  assert.match(accountManagementSource, /Reset student device/);
  assert.match(accountManagementSource, /getSummary/);
  assert.match(accountManagementSource, /limit: 25/);
  assert.match(accountManagementSource, /directory-table/);
  assert.match(accountManagementSource, /summary\.active/);
  assert.match(facultyStudentsSource, /assignedStudents/);
  assert.match(facultyStudentsSource, /Assigned students/);
  assert.match(changePasswordPageSource, /<PasswordField/);
  assert.match(changePasswordPageSource, /isStrongPassword/);
  assert.match(resetPasswordSource, /<PasswordField/);
  assert.match(resetPasswordSource, /isStrongPassword/);
  assert.match(forgotPasswordSource, /Reset code sent/);
  assert.match(forgotPasswordSource, /If an account matches/);
});

test('change-password uses the shared portal modal contract', () => {
  assert.match(modalSource, /createPortal/);
  assert.match(modalSource, /z-\[1100\]/);
  assert.match(modalSource, /aria-modal="true"/);
  assert.match(modalSource, /Escape/);
  assert.match(changePasswordSource, /<Modal isOpen=\{isOpen\}/);
  assert.match(changePasswordSource, /aria-label=\{visible \? `Hide \$\{label\}` : `Show \$\{label\}`\}/);
});


test('bootstrap refresh is shared and recoverable after a terminal failure', () => {
  const authContextSource = fs.readFileSync(new URL('../src/context/AuthContext.jsx', import.meta.url), 'utf8');
  assert.match(authContextSource, /if \(authBootstrapPromise\) return authBootstrapPromise/);
  assert.match(authContextSource, /if \(authBootstrapPromise === currentPromise\) authBootstrapPromise = null/);
  assert.match(authContextSource, /resetBootstrapSession\(\)/);
});

test('p28 responsive rendering and refresh boundaries remain explicit', () => {
  assert.match(indexCssSource, /@import ["']tailwindcss["'];/);
  assert.match(indexCssSource, /\.chart-frame/);
  assert.match(dashboardLayoutSource, /h-\[100dvh\]/);
  assert.match(dashboardLayoutSource, /min-h-0 min-w-0/);
  assert.match(trendChartSource, /height="100%"/);
  assert.match(trendChartSource, /minWidth=\{0\}/);
  assert.match(trendChartSource, /minTickGap/);
  assert.match(monthlyChartSource, /height="100%"/);
  assert.match(monthlyChartSource, /minWidth=\{0\}/);
  assert.match(subjectChartSource, /chartHeight/);
  assert.match(subjectChartSource, /height: `\$\{chartHeight\}px`/);
  assert.match(studentDashboardSource, /\/student\/scan-qr/);
  assert.doesNotMatch(peopleSource, /roleTabs|roleTab|<table/);
  assert.match(mainSource, /<StrictMode>/);
  assert.match(clientSource, /axios\.post\(`\$\{baseURL\}\/auth\/refresh`/);
  assert.match(clientSource, /config\.url\?\.includes\('\/auth\/refresh'\)/);
  assert.match(clientSource, /config\._retry/);
});

test('mobile navigation and global accessibility safeguards remain explicit', () => {
  assert.match(mobileNavSource, /role="dialog"/);
  assert.match(mobileNavSource, /aria-modal="true"/);
  assert.match(mobileNavSource, /event\.key === 'Escape'/);
  assert.match(mobileNavSource, /onClose/);
  assert.match(indexCssSource, /prefers-reduced-motion/);
  assert.match(indexHtmlSource, /rel="icon" type="image\/png" href="\/favicon\.png"/);
  assert.match(calendarDateSource, /DATE_ONLY_PREFIX/);
  assert.match(attendanceTrendSource, /formatCalendarDate\(entry\.date/);
  assert.match(indexCssSource, /overflow-x: hidden/);
  const workflowsSource = fs.readFileSync(new URL('../src/api/workflows.js', import.meta.url), 'utf8');
  assert.match(workflowsSource, /get: \(classId, config = \{\}\) => api\.get/);
  assert.match(workflowsSource, /availability: \(params, config = \{\}\) => api\.get/);
  assert.match(workflowsSource, /\.\.\.config, params/);
  assert.match(notificationsSource, /getFriendlyError/);
  assert.match(notificationsSource, /notificationApi\.list\(\{ page, limit: 25 \}\)/);
  assert.match(notificationsSource, /Notification history pagination/);
  assert.match(notificationsSource, /unreadCount/);
  assert.match(notificationPanelSource, /getFriendlyError/);
  assert.match(notificationPanelSource, /Retry loading notifications/);
  assert.match(notificationPanelSource, /Mark notification as read/);
  assert.match(notificationPanelSource, /busyAction/);
});


test('Faculty attendance period choices are exact-slot scoped and StrictMode-safe', () => {
  assert.match(facultyAttendanceSource, /useAuth/);
  assert.match(facultyAttendanceSource, /requestSingleFlight/);
  assert.match(facultyAttendanceSource, /faculty-periods/);
  assert.match(facultyAttendanceSource, /filterFacultyPeriods/);
  assert.match(facultyPeriodScopeSource, /period\.subject/);
  assert.match(facultyAttendanceSource, /selectedPeriod/);
  assert.match(facultyAttendanceSource, /faculty-roster/);
  assert.match(facultyAttendanceSource, /periodOrder: Number\(periodOrder\)/);
  assert.match(facultyQrSource, /filterFacultyPeriods/);
  assert.match(facultyQrSource, /faculty-periods/);
  assert.match(facultyQrSource, /selectedPeriod/);
  assert.match(facultyPeriodApiSource, /mySubjects: \(params = \{\}, config = \{\}\)/);
  assert.match(facultyPeriodApiSource, /getByDay: \(day, params, config = \{\}\)/);
  assert.match(singleFlightSource, /inFlightRequests/);
  assert.match(facultyPeriodScopeSource, /filterFacultyPeriods/);
  assert.match(facultyPeriodScopeSource, /period\.faculty/);
  assert.match(facultyPeriodScopeSource, /period\.subject/);
  assert.match(periodControllerSource, /ROLES\.ADMIN/);
  assert.match(periodControllerSource, /faculty-assigned-slots/);
  assert.match(periodControllerSource, /isSameId\(slot\.faculty, req\.user\._id\)/);
  assert.match(attendanceControllerSource, /You are not assigned to this exact timetable period/);
});

test('timetable, tutor, and leave workflows are present in the role-aware UI', () => {
  const timetableSource = fs.readFileSync(new URL('../src/pages/hod/PeriodsPage.jsx', import.meta.url), 'utf8');
  const workflowsSource = fs.readFileSync(new URL('../src/api/workflows.js', import.meta.url), 'utf8');
  assert.match(timetableSource, /Departments & semesters/);
  assert.match(timetableSource, /Assigned Faculty/);
  assert.match(timetableSource, /function cleanId\(value\)/);
  assert.match(timetableSource, /typeof value === 'object' \? value\._id \?\? value\.id : value/);
  assert.match(timetableSource, /\^\[0-9a-f\]\{24\}\$\/i\.test/);
  assert.match(timetableSource, /function normalizeTimetable\(value\)/);
  assert.match(timetableSource, /timetableApi\.get\(selectedClassId, \{ signal: controller\.signal \}\)/);
  assert.match(timetableSource, /subjectApi\.list\(\{ classId: selectedClassId, limit: 100 \}, \{ signal: controller\.signal \}\)/);
  assert.match(timetableSource, /excludeTimetableId: cleanId\(timetable\)/);
  assert.match(timetableSource, /slotId: cleanId\(slot\)/);
  assert.match(timetableSource, /Class tutor/);
  assert.match(timetableSource, /Busy Faculty members are hidden/);
  assert.match(timetableSource, /No active Faculty is available for this exact slot/);
  assert.match(timetableSource, /status: 'loading'/);
  assert.match(timetableSource, /status: faculty\.length \? 'success' : 'empty'/);
  assert.match(timetableSource, /status: 'error'/);
  assert.match(timetableSource, /AbortController/);
  assert.match(timetableSource, /subjectId: cleanId\(slot\.subject\)/);
  assert.match(timetableSource, /aria-label="Timetable days"/);
  assert.match(timetableSource, /Class period/);
  assert.match(timetableSource, /Assigned Faculty/);
  assert.match(timetableSource, /shadow-\[0_4px_16px/);
  assert.match(timetableSource, /controller\.abort\(\)/);
  assert.match(timetableSource, /slotId/);
  assert.match(timetableSource, /\.\.\.\(cleanId\(slot\) \? \{ _id: cleanId\(slot\) \} : \{\}\)/);
  assert.match(timetableSource, /setTimetable\(normalizeTimetable\(data\?\.data\?\.timetable/);
  assert.match(academicManagementSource, /Manage class tutor/);
  assert.match(academicManagementSource, /Confirm tutor change/);
  assert.match(academicManagementSource, /SUBJECT_PAGE_SIZE = 100/);
  assert.match(academicManagementSource, /async function loadAllSubjects/);
  assert.match(academicManagementSource, /loadAllSubjectPages/);
  assert.match(academicManagementSource, /pageSize: SUBJECT_PAGE_SIZE/);
  assert.match(studentLeaveSource, /Send one clear request to your class tutor and HOD/);
  assert.match(studentLeaveSource, /leaveApi\.create/);
  assert.match(studentLeaveSource, /This request was not approved/);
  assert.match(studentLeaveSource, /Next step/);
  assert.match(leaveReviewSource, /Rejection reason/);
  assert.match(leaveReviewSource, /length < 5/);
  assert.match(leaveReviewSource, /STATUS_ORDER/);
  assert.match(leaveReviewSource, /decidedBy/);
  assert.match(leaveReviewSource, /decidedAt/);
  assert.match(studentLeaveSource, /STATUS_ORDER/);
  assert.match(studentLeaveSource, /decidedBy/);
  assert.match(studentLeaveSource, /decidedAt/);
  assert.match(studentLeaveSource, /role="tab"/);
  assert.match(leaveReviewSource, /leaveApi\.decide/);
  assert.match(workflowsSource, /timetableApi/);
  assert.match(workflowsSource, /leaveApi/);
  assert.match(topbarSource, /className="ml-auto"/);
});


test('assignment request UI exposes Faculty inability and HOD replacement actions', () => {
  const assignmentSource = fs.readFileSync(new URL('../src/pages/shared/AssignmentRequestsPage.jsx', import.meta.url), 'utf8');
  const appSource = fs.readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8');
  const navigationSource = fs.readFileSync(new URL('../src/components/layout/navigation.js', import.meta.url), 'utf8');
  assert.match(assignmentSource, /Report inability/);
  assert.match(assignmentSource, /Send to HOD/);
  assert.match(assignmentSource, /Accept and replace/);
  assert.match(assignmentSource, /Reject and keep assignment/);
  assert.match(assignmentSource, /timetableApi\.availability/);
  assert.match(assignmentSource, /assignmentRequestApi\.decide/);
  assert.match(appSource, /AssignmentRequestsPage/);
  assert.match(navigationSource, /Cannot take a slot\?/);
  assert.match(navigationSource, /Assignment review/);
});


test('v26 responsive shell, dashboard, Tutors directory, and outside-dismiss menus remain explicit', () => {
  assert.match(hodDashboardSource, /MetricCard/);
  assert.match(hodDashboardSource, /totalStudents/);
  assert.match(hodDashboardSource, /\/hod\/tutors/);
  assert.match(dashboardLayoutSource, /2xl:max-w-\[96rem\]/);
  assert.match(desktopNavSource, /lg:flex/);
  assert.match(mobileNavSource, /lg:hidden/);
  assert.match(topbarSource, /lg:hidden/);
  assert.match(accountManagementSource, /PortalPopover/);
  assert.match(accountManagementSource, /onClose\(\)/);
  assert.match(modalSource, /onClick=\{onClose\}/);
});

test('v28 Messages UI provides role tabs, safe profiles, read ticks, and keyboard-friendly text compose', () => {
  const messagesPageSource = fs.readFileSync(new URL('../src/pages/shared/MessagesPage.jsx', import.meta.url), 'utf8');
const messagesApiSource = fs.readFileSync(new URL('../src/api/messages.js', import.meta.url), 'utf8');
  const uploadsSource = fs.readFileSync(new URL('../src/api/uploads.js', import.meta.url), 'utf8');
  const tutorsPageSource = fs.readFileSync(new URL('../src/pages/hod/TutorsPage.jsx', import.meta.url), 'utf8');
  assert.match(topbarSource, /requestSingleFlight/);
  assert.match(topbarSource, /notifications-unread/);
  assert.match(appSource, /MessagesPage/);
  assert.match(appSource, /path="messages"/g);
  assert.match(navigationSource, /MessagesSquare/);
  assert.match(navigationSource, /\/hod\/messages/);
  assert.match(navigationSource, /\/faculty\/messages/);
  assert.match(navigationSource, /\/student\/messages/);
  assert.match(messagesPageSource, /GROUPS_BY_ROLE/);
  assert.match(messagesPageSource, /key: 'students'/);
  assert.match(messagesPageSource, /key: 'all'/);
  assert.match(messagesPageSource, /key: 'faculty'/);
  assert.match(messagesPageSource, /key: 'hod'/);
  assert.match(messagesPageSource, /key: 'tutors'/);
  assert.match(messagesPageSource, /super_admin: \[[\s\S]*key: 'tutors'/);
  assert.match(messagesPageSource, /admin: \[[\s\S]*key: 'hod'/);
  assert.match(messagesPageSource, /user: \[[\s\S]*key: 'hod'/);
  assert.match(messagesPageSource, /messagesApi\.recipients/);
  assert.match(messagesPageSource, /startConversation/);
  assert.match(messagesPageSource, /recipientResults/);
  assert.match(messagesPageSource, /Add chat/);
  assert.match(messagesPageSource, /isAddChatOpen/);
  assert.match(messagesPageSource, /message-recipient-query/);
  assert.match(messagesPageSource, /Only people you are authorized to message will appear/);
  assert.doesNotMatch(messagesPageSource, /message-recipient-search-panel|message-recipient-groups|groupedRecipients/);
  assert.match(messagesPageSource, /GROUPS_BY_ROLE/);
  assert.match(messagesPageSource, /role="tablist"/);
  assert.match(messagesPageSource, /conversationGroup/);
  assert.match(messagesPageSource, /setConversationGroup/);
  assert.doesNotMatch(messagesPageSource, /setRecipientGroup|recipientGroup/);
  assert.doesNotMatch(messagesPageSource, /showNewMessage/);
  assert.match(messagesPageSource, /messagesApi\.profile/);
  assert.match(messagesPageSource, /messagesApi\.conversations/);
  assert.match(messagesPageSource, /messagesApi\.markRead/);
  assert.match(messagesPageSource, /messagesApi\.send/);
  assert.match(messagesPageSource, /unreadCount/);
  assert.doesNotMatch(messagesPageSource, /unreadByRecipient/);
  assert.match(messagesPageSource, /bg-emerald-600/);
  assert.match(messagesPageSource, /No conversations in this group/);
  assert.match(messagesPageSource, /No conversations in this group|Choose a contact or thread to start chatting/);
  assert.match(messagesPageSource, /requestSingleFlight/);
  assert.match(messagesPageSource, /MessageBubble/);
  assert.match(messagesPageSource, /Edit3/);
  assert.match(messagesPageSource, /Trash2/);
  assert.match(messagesPageSource, /Delete from me/);
  assert.match(messagesPageSource, /Delete from everyone/);
  assert.match(messagesPageSource, /handleDeleteMessage/);
  assert.match(messagesPageSource, /It will be removed from the conversation/);
  const qrAttendanceSource = fs.readFileSync(new URL('../src/pages/faculty/QrAttendancePage.jsx', import.meta.url), 'utf8');
  assert.match(qrAttendanceSource, /Students can scan this QR or copy the secure link to mark attendance securely\./);
  assert.match(messagesApiSource, /edit:/);
  assert.match(messagesApiSource, /remove:/);
  assert.match(messagesPageSource, /message-recipients:/);
  assert.match(messagesPageSource, /message-conversations:/);
  assert.match(messagesPageSource, /message-thread:/);
  assert.match(pendingRegistrationSource, /RefreshCw/);
  assert.match(pendingRegistrationSource, /load\(\{ refresh: true \}\)/);
  assert.match(pendingRegistrationSource, /request\.status === activeTab/);
  assert.match(messagesPageSource, /recipientRequestRef/);
  assert.match(messagesPageSource, /conversationRequestRef/);
  assert.match(messagesPageSource, /CheckCheck/);
  assert.match(messagesPageSource, /readAt/);
  assert.match(messagesPageSource, /handleComposerKeyDown/);
  assert.match(messagesPageSource, /event\.shiftKey/);
  assert.match(messagesPageSource, /setInterval/);
  assert.match(messagesPageSource, /maxLength=\{MAX_BODY_LENGTH\}/);
  assert.doesNotMatch(messagesPageSource, /Sensitive credentials|Text only · maximum|uploadApi|multipart|type="file"|video|audio/);
  assert.match(messagesPageSource, /SkeletonTable/);
  assert.match(messagesPageSource, /role="alert"/);
  assert.match(messagesApiSource, /\/messages\/profiles/);
  assert.match(messagesApiSource, /\/messages\/recipients/);
  assert.match(messagesApiSource, /\/messages\/conversations/);
  assert.match(messagesApiSource, /markRead/);
  assert.match(messagesApiSource, /send: \(conversationId, payload\)/);
  assert.doesNotMatch(uploadsSource, /messageAttachment|message-attachment/);
  assert.match(tutorsPageSource, /tutorsOnly/);
});


test('refresh failure handling is epoch-aware and preserves single-flight session safety', () => {
  assert.match(clientSource, /runSingleFlight/);
  assert.match(clientSource, /config\._authEpoch === authEpoch/);
  assert.match(clientSource, /Do not invalidate a newer session/);
  assert.match(clientSource, /axios\.post\(`\$\{baseURL\}\/auth\/refresh`/);
});


test('Messages polling pauses off-screen and cleans up visibility listeners', () => {
  const messagesSource = fs.readFileSync(new URL('../src/pages/shared/MessagesPage.jsx', import.meta.url), 'utf8');
  assert.match(messagesSource, /document\.visibilityState === 'visible'/);
  assert.match(messagesSource, /document\.addEventListener\('visibilitychange', refreshWhenVisible\)/);
  assert.match(messagesSource, /document\.removeEventListener\('visibilitychange', refreshWhenVisible\)/);
});


test('network failures use an actionable connection message', () => {
  assert.match(errorMessagesSource, /ECONNREFUSED/);
  assert.match(errorMessagesSource, /ETIMEDOUT/);
  assert.match(errorMessagesSource, /Boolean\(error\.request\)/);
  assert.match(errorMessagesSource, /We could not reach the server/);
});
