import { format, formatDistanceToNow } from 'date-fns';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { AlertTriangle, ArrowRight, Building2, CalendarCheck2, CalendarDays, FileBarChart2, GraduationCap, RefreshCw, UsersRound } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext.jsx';
import { dashboardApi } from '../../api/misc.js';
import Button from '../../components/common/Button.jsx';
import Badge from '../../components/common/Badge.jsx';
import EmptyState from '../../components/common/EmptyState.jsx';
import AttendanceTrendChart from '../../components/charts/AttendanceTrendChart.jsx';
import { fadeUp } from '../../utils/motion.js';
import { getFriendlyError } from '../../utils/errorMessages.js';

function DashboardSkeleton() {
  return <div className="space-y-5" aria-busy="true" aria-label="Loading HOD dashboard"><div className="skeleton h-24" /><div className="grid gap-4 lg:grid-cols-[1.35fr_0.65fr]"><div className="skeleton h-64" /><div className="skeleton h-64" /></div><div className="skeleton h-28" /><div className="skeleton h-72" /></div>;
}

function MetricCard({ icon: Icon, label, value, detail, to }) {
  const content = <><div className="flex items-start justify-between gap-4"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-light text-indigo transition-colors group-hover:bg-ink group-hover:text-paper"><Icon size={18} aria-hidden="true" /></span>{to && <ArrowRight size={16} className="text-slate transition-transform group-hover:translate-x-1" aria-hidden="true" />}</div><p className="eyebrow mt-7">{label}</p><strong className="mt-2 block font-display text-[clamp(1.8rem,3vw,2.55rem)] font-semibold tracking-[-0.06em] text-ink">{value}</strong><p className="mt-1 text-xs text-slate">{detail}</p></>;
  return to ? <Link to={to} className="group min-w-0 border border-line bg-surface p-5 transition-colors hover:border-indigo/40 hover:bg-indigo-light/20 focus:outline-none focus:ring-2 focus:ring-indigo/20 sm:p-6">{content}</Link> : <div className="min-w-0 border border-line bg-surface p-5 sm:p-6">{content}</div>;
}

function NumberRow({ icon: Icon, label, value, to }) {
  const content = <><Icon size={16} className="text-slate" aria-hidden="true" /><span className="flex-1 text-sm text-slate">{label}</span><strong className="font-display text-lg font-semibold text-ink">{value}</strong></>;
  return to ? <Link to={to} className="flex items-center gap-3 border-b border-line py-3 transition-colors hover:bg-paper-dim/60 last:border-b-0"><span className="flex flex-1 items-center gap-3">{content}</span><ArrowRight size={15} className="text-slate" aria-hidden="true" /></Link> : <div className="flex items-center gap-3 border-b border-line py-3 last:border-b-0">{content}</div>;
}

function AttendancePulse({ today = {}, monthly = {} }) {
  const percentage = Math.max(0, Math.min(100, Number(today.percentage || 0)));
  return <section className="min-w-0 border border-line bg-surface p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Today across the institution</p><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-0.04em] text-ink">Attendance pulse</h2><p className="mt-1 text-sm text-slate">A live view of records marked today, not a projected value.</p></div><div className="flex h-10 w-10 items-center justify-center rounded-full bg-accent-light text-accent"><CalendarCheck2 size={19} /></div></div><div className="mt-8 flex flex-col gap-6 sm:flex-row sm:items-end"><div><p className="font-display text-4xl font-semibold tracking-[-0.07em] text-ink sm:text-5xl">{percentage}%</p><p className="mt-2 text-sm text-slate">{today.present || 0} present of {today.total || 0} recorded</p></div><div className="min-w-0 flex-1 pb-2"><div className="mb-2 flex justify-between text-xs font-semibold text-slate"><span>Present or late</span><span>{today.total ? `${today.total - (today.present || 0)} absent or other` : 'No records yet'}</span></div><div className="h-3 overflow-hidden bg-paper-dim"><div className="h-full bg-sage transition-[width] duration-500" style={{ width: `${percentage}%` }} /></div></div></div><div className="mt-7 border-t border-line pt-4 text-sm text-slate"><span className="font-semibold text-ink">This month:</span> {monthly.present || 0} of {monthly.total || 0} records attended · {monthly.percentage || 0}%</div></section>;
}

function ActionRail() {
  const actions = [['Students', 'Open the learner directory', '/hod/students', GraduationCap], ['Faculty', 'Review teaching staff', '/hod/faculty', UsersRound], ['Tutors', 'See assigned class tutors', '/hod/tutors', UsersRound], ['Academic structure', 'Departments, classes, subjects', '/hod/academics', Building2], ['Reports', 'Inspect attendance exports', '/hod/reports', FileBarChart2]];
  return <nav className="grid min-w-0 border-y border-line bg-surface sm:grid-cols-2 lg:grid-cols-4" aria-label="HOD actions">{actions.map(([label, detail, to, Icon]) => <Link key={to} to={to} className="group flex items-center gap-3 border-b border-line px-4 py-4 transition-colors hover:bg-paper-dim/65 sm:nth-[2n]:border-l lg:border-b-0 lg:border-l lg:first:border-l-0"><span className="flex h-9 w-9 items-center justify-center bg-ink text-paper"><Icon size={16} /></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-ink">{label}</span><span className="mt-0.5 block truncate text-xs text-slate">{detail}</span></span><ArrowRight size={15} className="text-slate transition-transform group-hover:translate-x-1" /></Link>)}</nav>;
}

function FlaggedStudents({ students, count }) {
  return <section className="min-w-0 border border-line bg-surface"><div className="flex flex-col gap-3 border-b border-line px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Intervention queue</p><h2 className="mt-2 font-display text-xl font-semibold text-ink">Students needing attention</h2></div><div className="flex items-center gap-3"><Badge variant={count ? 'absent' : 'present'}>{count} flagged</Badge><Link to="/hod/students" className="inline-flex items-center gap-1 text-xs font-semibold text-ink hover:text-accent">Open students <ArrowRight size={13} /></Link></div></div>{students.length === 0 ? <div className="px-5 py-8"><EmptyState icon={AlertTriangle} title="No students flagged" message="No recorded attendance is below the review threshold." /></div> : <div className="overflow-x-auto"><table className="directory-table min-w-[650px] w-full text-sm"><caption className="sr-only">Students below attendance threshold</caption><thead><tr><th>Student</th><th>Register number</th><th>Class</th><th>Attendance</th><th>Status</th></tr></thead><tbody>{students.slice(0, 10).map((student) => <tr key={student.studentId}><td className="font-semibold text-ink">{student.name}</td><td className="font-mono text-xs text-slate">{student.registerNumber || '—'}</td><td className="text-slate">{student.className || '—'}</td><td className="font-semibold text-ink">{student.percentage}%</td><td><Badge variant={student.percentage < 60 ? 'absent' : 'late'}>{student.percentage < 60 ? 'Critical' : 'Review'}</Badge></td></tr>)}</tbody></table></div>}</section>;
}

function ActivityList({ activities }) {
  return <section className="min-w-0 border border-line bg-surface"><div className="border-b border-line px-5 py-5"><p className="eyebrow">Audit trail</p><h2 className="mt-2 font-display text-xl font-semibold text-ink">Recent activity</h2></div>{activities.length === 0 ? <div className="px-5 py-8"><EmptyState title="No recent activity" message="Important institution actions will appear here." /></div> : <div className="divide-y divide-line">{activities.slice(0, 6).map((activity) => <div key={activity._id} className="flex items-start gap-3 px-5 py-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-paper-dim text-xs font-bold text-ink">{activity.actor?.name?.[0]?.toUpperCase() || 'S'}</span><div className="min-w-0 flex-1"><p className="text-sm leading-5 text-ink"><strong>{activity.actor?.name || 'System'}</strong> {activity.description}</p><p className="mt-1 text-xs text-slate">{formatDistanceToNow(new Date(activity.createdAt), { addSuffix: true })}</p></div></div>)}</div>}
</section>;
}

export default function HodDashboardPage() {
  const { user } = useAuth();
  const [data, setData] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const loadDashboard = useCallback(async () => { setIsLoading(true); setError(''); try { const { data: response } = await dashboardApi.hod(); setData(response.data); } catch (err) { setError(getFriendlyError(err, 'We could not retrieve the latest institution data. Please try again.')); } finally { setIsLoading(false); } }, []);
  useEffect(() => { loadDashboard(); }, [loadDashboard]);
  if (isLoading) return <DashboardSkeleton />;
  if (error || !data) return <div className="notice-error" role="alert"><AlertTriangle size={18} /><div className="flex-1"><p className="font-semibold">Unable to load the HOD overview</p><p className="mt-1 text-sm">{error || 'No dashboard data was returned.'}</p><Button type="button" variant="outline" icon={RefreshCw} className="mt-4" onClick={loadDashboard}>Try again</Button></div></div>;
  const { totals = {}, todayAttendance = {}, monthlyAttendance = {}, lowAttendanceStudents = [], lowAttendanceCount = 0, recentActivity = [], attendanceTrend = [] } = data;
  return <motion.div className="space-y-6" {...fadeUp}><header className="flex flex-col gap-3 border-b border-line pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-accent">Head of Department workspace</p><h1 className="page-title mt-2">Institution overview</h1><p className="page-lede mt-2">Good to see you, {user?.name?.split(' ')?.[0] || 'there'}. Your authorized view spans academics, accounts, and attendance.</p></div><span className="flex items-center gap-2 text-xs font-semibold text-slate"><CalendarDays size={15} />{format(new Date(), 'EEEE, d MMMM yyyy')}</span></header><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 2xl:gap-5"><MetricCard icon={GraduationCap} label="Students" value={totals.totalStudents || 0} detail="Enrolled learners" to="/hod/students" /><MetricCard icon={UsersRound} label="Faculty" value={totals.totalFaculty || 0} detail="Teaching staff" to="/hod/faculty" /><MetricCard icon={Building2} label="Departments" value={totals.totalDepartments || 0} detail="Academic departments" to="/hod/academics" /><MetricCard icon={CalendarDays} label="Classes" value={totals.totalClasses || 0} detail="Active class groups" to="/hod/academics" /></div><div className="grid gap-4 lg:grid-cols-[1.35fr_0.65fr]"><AttendancePulse today={todayAttendance} monthly={monthlyAttendance} /><section className="border border-line bg-surface p-5"><p className="eyebrow">Operational focus</p><h2 className="mt-2 font-display text-xl font-semibold text-ink">What needs review</h2><div className="mt-4"><NumberRow icon={AlertTriangle} label="Low attendance queue" value={lowAttendanceCount} to="/hod/students" /><NumberRow icon={FileBarChart2} label="Monthly records" value={monthlyAttendance.total || 0} to="/hod/reports" /><NumberRow icon={CalendarCheck2} label="Today’s records" value={todayAttendance.total || 0} /></div></section></div><ActionRail /><section className="min-w-0 border border-line bg-surface p-4 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-line pb-4"><div><p className="eyebrow">Attendance trend</p><h2 className="mt-2 font-display text-xl font-semibold text-ink">Last fourteen days</h2></div><Link to="/hod/reports" className="inline-flex items-center gap-1 text-xs font-semibold text-ink hover:text-accent">Open reports <ArrowRight size={13} /></Link></div><div className="pt-5">{attendanceTrend.length ? <AttendanceTrendChart data={attendanceTrend} /> : <EmptyState icon={CalendarCheck2} title="No trend data yet" message="The chart will appear after attendance is recorded." />}</div></section><FlaggedStudents students={lowAttendanceStudents} count={lowAttendanceCount} /><ActivityList activities={recentActivity} /></motion.div>;
}
